kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "frontend-as-service"
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/LEADSNGFS/fronted-as-service'
    sourceSecret:
      name: github-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile
    type: JenkinsPipeline
