apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build:production-[buildname]
  name: production-[buildname]
  namespace: [projectname]
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ['imagename']
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk:8-jdk-alpine'
    type: Docker

